---
- name: restart sshd
  service:
    name: sshd
    state: restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Debian'

- name: restart ssh
  service:
    name: ssh
    state: restarted
  when: ansible_distribution == 'Ubuntu'
